version: '3.6'
services:
  traefik:
    ports:
      - "8081:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.dev.toml:/etc/traefik/traefik.toml"

  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`yearn-roi.localhost`)"

  backend:
    ports:
      - '5000:5000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`yearn-roi.localhost`)"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/`)"

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./data/dev-db-mysql:/var/lib/mysql
