version: '3.6'
services:
  traefik:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.prod.toml:/etc/traefik/traefik.toml"

  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`www.yearn-roi.xyz`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"

  backend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`www.yearn-roi.xyz`)"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./database/db-mysql:/var/lib/mysql

