version: '3.6'
services:
  traefik:
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.prod.toml:/etc/traefik/traefik.toml"
      - "./traefik/acme.json:/acme.json"

  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`www.yearn-roi.xyz`)"
      - "traefik.http.routers.frontend.tls=true"
      - 'traefik.http.routers.frontend.tls.domains[0].main=www.yearn-roi.xyz'
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"

  backend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`www.yearn-roi.xyz`)"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/`)"
      - "traefik.http.routers.backend.tls=true"
      - 'traefik.http.routers.backend.tls.domains[0].main=www.yearn-roi.xyz'
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./data/db-mysql:/var/lib/mysql

